### ISSUE TITLE
Letsencrypt ACMEv1 eol plan

### ISSUE THREAD

**Issue by HillLiu** [pmvc/heroku-config#3]
## Announcements
https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430

## Some Issues
* https://github.com/dokku/dokku-letsencrypt/issues/148
   * certbot
   * [certbot running with docker](https://certbot.eff.org/docs/install.html#running-with-docker)
* https://github.com/dokku/dokku-letsencrypt/issues/147
   * [simp_le](https://github.com/zenhack/simp_le)
* final solution
   * https://github.com/dokku/dokku-letsencrypt/issues/183#issuecomment-541274696

**Comment by josegonzalez** [comment]
We support  ACME v2 now.

**Comment by HillLiu** [comment]
Close by v2 out
